mypy typecheck
mosquito/aiohttp-s3-client pull request #8
Opened 2021-03-28 08:35 UTC by asteny

2021-03-31 19:06 UTC, mosquito approved these changes

2021-04-04 10:38 UTC, alvassin requested changes

2021-04-04 10:38 UTC, alvassin commented on aiohttp_s3_client/client.py
> +            headers[hdrs.CONTENT_TYPE] = str(guess_type(file_path)[0])
а зачем тут str?

2021-04-04 10:52 UTC, asteny commented on aiohttp_s3_client/client.py
> +            headers[hdrs.CONTENT_TYPE] = str(guess_type(file_path)[0])
разобрались, запушил изминения

2021-04-04 10:54 UTC, alvassin approved these changes

2021-04-04 10:54 UTC, merged